<a href="https://colab.research.google.com/github/abhinavg04/Pytorch-tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#Addition long hand
torch.add(tensor_b,tensor_a)

tensor([ 6,  8, 10, 12])

In [5]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
#sub function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [7]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
#MUl longhand
torch.mul(tensor_b,tensor_a)

tensor([ 5, 12, 21, 32])

In [10]:
#Division
tensor_b / tensor_a  #torch.div()

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
tensor_b % tensor_a  #torch.reminder

tensor([0, 0, 1, 0])

In [13]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#re assignemt
tensor_a = tensor_a+tensor_b
#or
tensor_a.add_(tensor_b)